[package]
name = "bitcredit"
version = "0.1.0"
edition = "2021"

[dependencies]
openssl = "0.10.40"
borsh = "0.10.0"
libp2p = { version = "0.50.0" }
tokio = { version = "1.0", features = ["io-util", "io-std", "macros", "rt", "rt-multi-thread", "sync", "fs"] }
chrono = "0.4.23"
rocket = { version = "0.5.0-rc.2", features = ["json"] }
rocket_dyn_templates = { version = "0.1.0-rc.2", features = ["handlebars"] }
rocket_contrib = "0.4.11"
