name: Qodana

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - main
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.2.9
        env:
          QODANA_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJvcmdhbml6YXRpb24iOiJ6OGdSYiIsInByb2plY3QiOiJBWWp2USIsInRva2VuIjoiM2VlUTEifQ.8MAwl__NYsdJnYZ9lacQbROCYLdukwWXDjS08xOqXb8